name: sanchu4
description: 天運三柱推命ver.4

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
    #firebase_analytics: ^8.2.0
  cloud_firestore: ^4.2.0
    #firebase_storage: ^10.0.3
    #firebase_auth: ^3.1.0
    #image_picker: ^0.8.4


  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - images/main/gogyou1.png
    - images/main/taxi.png
    - images/nikkan/甲_大樹.jpg
    - images/nikkan/甲_木陰.jpg
    - images/nikkan/丁_キャンドル.jpg
    - images/nikkan/丁_燃える炎.jpg
    - images/nikkan/丙_太陽.jpg
    - images/nikkan/丙_朝日.jpg
    - images/nikkan/乙_からみつく.jpg
    - images/nikkan/乙_イラスト１.jpg
    - images/nikkan/壬_支流.jpg
    - images/nikkan/壬_海.jpg
    - images/nikkan/己_畑土.jpg
    - images/nikkan/己_陶芸.jpg
    - images/nikkan/庚_剣.jpg
    - images/nikkan/庚_鍛える.jpg
    - images/nikkan/戊_岩山.jpg
    - images/nikkan/戊_石垣.jpg
    - images/nikkan/癸_潤う.jpg
    - images/nikkan/癸_雲雨.jpg
    - images/nikkan/辛_宝石.jpg
    - images/nikkan/辛_王冠.jpg
    - images/tentitokugou/anehaturu.jpg
    - images/tentitokugou/anehaturu1.jpg
    - images/tentitokugou/anehaturu2.jpg